language: node_js
node_js:
  - "0.10"

script: "tries=0; while [ $tries -lt 50 ]; do tries=$((tries+1)); echo ' -- TRY: '$tries; ./test/run 'test/unit/node' > /tmp/out 2>&1; if [ $? -ne 0 ]; then cat /tmp/out; exit 1; fi done"

